name: Deploy Test

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    environment: TEST_ENV

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file from secret
        run: echo "${{ secrets.ENV }}" > .env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t reborn-api .

      - name: Save Docker image to archive
        run: docker save reborn-api -o image.tar

      - name: Fix permissions for image.tar
        run: chmod +r image.tar

      - name: Copy image + .env to server via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: 'image.tar,.env'
          target: '/home/${{ secrets.SSH_USER }}/deploy'

      - name: SSH and run container
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/deploy
            docker load -i image.tar
            docker stop reborn-api || true && docker rm reborn-api || true
            docker run -d --name reborn-api \
              --env-file .env \
              --network host \
              -p 5001:5000 \
              reborn-api